version: '3.3'
services:
  db:
    image: mysql:8.1.0
    restart: "always"
    environment:
      MYSQL_DATABASE: 'plants-diary-db'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'